collective: statusfy
invitation: |
  Hey <author> :wave:, Thank you for opening an issue.

  Check out our OpenCollective and consider backing us. Help us to **continue developing** this Amazing Project, **we will appreciate it** :heart:.
  You can contribute from $2 :nerd_face:, less than a cup of coffee :coffee: :smiley:

  <link>

  PS.: We offer `priority` support for all backers. Don't forget to add `priority` label when you start backing us :smile:
